[package]
name = "conway-life"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.26.1"
serde = { version = "1.0.174", features = ["derive"] }
serde_yaml = "0.9.25"
thiserror = "1.0.43"
tui = "0.19.0"
